# Generated by Django 5.0.2 on 2024-02-21 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='D_Date',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='D_Depart',
            fields=[
                ('code_region', models.IntegerField()),
                ('code_depart', models.IntegerField()),
                ('label_region', models.CharField(default=None, max_length=100)),
                ('label_depart', models.CharField(default=None, max_length=100)),
                ('pk_depart', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='D_Type',
            fields=[
                ('label', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ODS_FTD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_region', models.CharField(default='0', max_length=100)),
                ('libelle_region', models.CharField(default='0', max_length=100)),
                ('code_departement', models.CharField(default='0', max_length=100)),
                ('libelle_departement', models.CharField(default='0', max_length=100)),
                ('date_fin_semaine', models.CharField(default='0', max_length=100)),
                ('type_de_vaccin', models.CharField(default='0', max_length=100)),
                ('nb_ucd', models.CharField(default='0', max_length=100)),
                ('nb_doses', models.CharField(default='0', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='F_Dose',
            fields=[
                ('nb_ucd', models.IntegerField()),
                ('nb_dose', models.IntegerField()),
                ('pk_dose', models.CharField(default=None, max_length=100, primary_key=True, serialize=False)),
                ('Date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_date')),
                ('Depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_depart')),
                ('Type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.d_type')),
            ],
        ),
    ]
