# Generated by Django 5.0.2 on 2024-02-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_depart',
            name='code_depart',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='d_depart',
            name='code_region',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
