# Generated by Django 5.0.2 on 2024-03-04 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_ods_ftd_code_departement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ods_ftd',
            name='code_departement',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ods_ftd',
            name='code_region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ods_ftd',
            name='date_fin_semaine',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ods_ftd',
            name='libelle_departement',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ods_ftd',
            name='libelle_region',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ods_ftd',
            name='nb_doses',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ods_ftd',
            name='nb_ucd',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ods_ftd',
            name='type_de_vaccin',
            field=models.CharField(max_length=100),
        ),
    ]
